Character-Helper/Models/CharacterCreationViewModel.cs
using System.Net.NetworkInformation;

namespace Character_Helper.Models
{
    public class CharacterCreationViewModel
    {
        public CharacterViewModel Character { get; set; }
        public List<PlayerViewModel> Players { get; set; }
    }
}

Character-Helper/Models/CharacterViewModel.cs
/*
 * I applied OCP or the Open/Closed Principle to my CharacterViewModel. This model needs to be mostly closed to modification as it is tied to the database.
 * But there are situations where I need this and more, which is how it is open to extension. For creating characters I can only pass one model to the view,
 * I need this CharacterViewModel because that is what is being created but I need a list of all players to choose one from as ther is a one(player) to many(characters) relationship.
 * So, I extended this CharacterViewModel and the PlayerViewModel in a way, I created the CharacterCreationViewModel as a specific tool for this purpose that has no affect on
 * either model it takes from, it has a CharacterViewModel as a property and a list of PlayerViewModels as another. This way I was able to pass everything to the Character Create
 * page without crudely modifying the pre-existing models.
 */

namespace Character_Helper.Models
{
    public class CharacterViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int PlayerId { get; set; }
        public PlayerViewModel Player { get; set; }
        public string Class { get; set; }
        public int Level { get; set; }
        public int Strength { get; set; }
        public int Dexterity { get; set; }
        public int Constitution { get; set; }
        public int Intelligence { get; set; }
        public int Wisdom { get; set; }
        public int Charisma { get; set; }

        public int GetMod(int stat)
        {
            if(stat%2 != 0)
            {
                stat = stat - 1;
            }
            return (stat-10)/2;
        }
    }
}

Character-Helper/Models/ErrorViewModel.cs
namespace Character_Helper.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Character-Helper/Models/PlayerViewModel.cs
using System.ComponentModel.DataAnnotations;
namespace Character_Helper.Models
{
    public class PlayerViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        
        [RegularExpression(@"^1?(\s|-)?\(?\d{3}\)?(\s|-|\s-)?\d{3}(\s|-)\d{4}?$")]
        public string PhoneNumber { get; set; }
        public ICollection<CharacterViewModel> Characters { get; set; }
    }
}

Character-Helper/Controllers/CharacterController.cs
using Character_Helper.Data;
using Character_Helper.Models;
using Microsoft.AspNetCore.Mvc;

namespace Character_Helper.Controllers
{
    public class CharacterController : Controller
    {

        private static List<CharacterViewModel> chars = new List<CharacterViewModel>();

        private readonly ApplicationDbContext _context;
        public CharacterController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            chars = _context.Characters.ToList();
            return View(chars);
        }

        public IActionResult Create()
        {
            CharacterCreationViewModel ccvm = new CharacterCreationViewModel();
            ccvm.Character = new CharacterViewModel();
            ccvm.Players = _context.Players.ToList();
            //CharacterViewModel charVM = new CharacterViewModel();
            return View(ccvm);
        }
        
        public IActionResult CreateCharacter(CharacterCreationViewModel ccvm)
        {
            _context.Characters.Add(ccvm.Character);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Character-Helper/Controllers/HomeController.cs
using Character_Helper.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Character_Helper.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Character-Helper/Controllers/PlayerController.cs
using Character_Helper.Data;
using Character_Helper.Models;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Character_Helper.Controllers
{
    public class PlayerController : Controller
    {
        private static List<PlayerViewModel> players = new List<PlayerViewModel>();

        private readonly ApplicationDbContext _context;

        public PlayerController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            players = _context.Players.ToList();
            return View(players);
        }

        public IActionResult Create()
        {
            var playerVM = new PlayerViewModel();
            return View(playerVM);
        }

        public IActionResult CreatePlayer(PlayerViewModel playerVM)
        {
            _context.Players.Add(playerVM);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Character-Helper/Views/Character/Create.cshtml
@model CharacterCreationViewModel
@{
    
}
<h1>Create Character</h1>

<hr />

<div class="row">
    <div class="col">

        <div class="card">
            <div class="card-header">
                <h5>Create a new Character</h5>
            </div>
            <div class="card-body">
                <form asp-controller="Character" asp-action="CreateCharacter" method="post">
                    <div class="mb-3">
                        <label class="form-label">Character Name</label>
                        <input asp-for="Character.Name" type="text" class="form-control" required/>
                    </div>
                    <div class="mb-3">  
                        <label class="form-label">Player</label>
                        <select class="form-control" asp-for="Character.PlayerId">
                            @foreach (var player in Model.Players)
                            {
                                <option value="@player.Id">@player.Name</option>
                            }
                        </select>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Class</label>
                        <input asp-for="Character.Class" type="text" class="form-control" required/>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Level</label>
                        <input asp-for="Character.Level" type="number" class="form-control" />
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Strength</label>
                        <input asp-for="Character.Strength" type="number" class="form-control" />
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Dexterity</label>
                        <input asp-for="Character.Dexterity" type="number" class="form-control" />
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Constitution</label>
                        <input asp-for="Character.Constitution" type="number" class="form-control" />
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Intelligence</label>
                        <input asp-for="Character.Intelligence" type="number" class="form-control" />
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Wisdom</label>
                        <input asp-for="Character.Wisdom" type="number" class="form-control" />
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Charisma</label>
                        <input asp-for="Character.Charisma" type="number" class="form-control" />
                    </div>
                    <div class="mb-3">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
            <div class="card-footer">
            </div>
        </div>
    </div>
</div>

Character-Helper/Views/Character/Index.cshtml
@model List<Character_Helper.Models.CharacterViewModel>
<h1>Characters</h1>
<a asp-area="" asp-controller="Character" asp-action="Create">Create Character</a>
@foreach (var character in Model){
    <table class="mb-3">
        <tr>
            <th colspan="3">
                <h3>@character.Name</h3>
                <h5>lvl @character.Level @character.Class</h5>
            </th>
        </tr>
        <tr>
            <td>
                Str @character.Strength (@character.GetMod(character.Strength))
            </td>
            <td>
                Dex @character.Dexterity (@character.GetMod(character.Dexterity))
            </td>
            <td>
                Con @character.Constitution (@character.GetMod(character.Constitution))
            </td>
        </tr>
        <tr>
            <td>
                Int @character.Intelligence (@character.GetMod(character.Intelligence))
            </td>
            <td>
                Wis @character.Wisdom (@character.GetMod(character.Wisdom))
            </td>
            <td>
                Cha @character.Charisma (@character.GetMod(character.Charisma))
            </td>
        </tr>
    </table>
}

Character-Helper/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    /*
     * MVC lends itself well to SOLID principles, but you still have to be mindful of them. I would note most clearly the Single Responsibility Principle,
     * looking at the views both models/tables have their own Index page for viewing listed data from the database and a separate Create page for adding rows of data to the database,
     * with the models being seperate only defining themselves and the controllers just handle the actions.
     */
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Add your players and their characters. Keep track of them here</p>
</div>

Character-Helper/Views/Player/Create.cshtml
@model PlayerViewModel

<h1>Create Player</h1>

<hr />

<div class="row">
    <div class="col">

        <div class="card">
            <div class="card-header">
                <h5>Create a new Character</h5>
            </div>
            <div class="card-body">
                <form asp-controller="Player" asp-action="CreatePlayer" method="post" onsubmit="return ValidatePhoneNumber();">
                    <div class="mb-3">
                        <label class="form-label">Player Name</label>
                        <input asp-for="Name" type="text" class="form-control" required />
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Phone Number</label>
                        <input asp-for="PhoneNumber" type="text" class="form-control" id="txtPhone" required />
                        <span id="phoneError" style="color:darkred"></span>
                        <script type="text/javascript">
                            function ValidatePhoneNumber() {
                                var phone = document.getElementById("txtPhone").value;
                                var error = document.getElementById("phoneError");
                                error.innerHTML = "";
                                var regex = /^1?(\s|-)?\(?\d{3}\)?(\s|-|\s-)?\d{3}(\s|-)\d{4}?$/;
                                if (!regex.test(phone)) {
                                    error.innerHTML = "Invalid phone number.";
                                    return false;
                                } else {
                                    return true;
                                }
                            }
                        </script>
                    </div>
                    <div class="mb-3">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
            <div class="card-footer">
            </div>
        </div>
    </div>
</div>

Character-Helper/Views/Player/Index.cshtml
@model List<Character_Helper.Models.PlayerViewModel>
<h1>Players</h1>
<button class="btn btn-primary" asp-area="" asp-controller="Player" asp-action="Create">Create Player</button>
<table>
    @foreach (var player in Model)
    {
        <tr class="mb-3">
            <th>
                <h5>@player.Name</h5>
            </th>
            <td>
                @player.PhoneNumber
            </td>
        </tr>
    }
</table>

Character-Helper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Character_Helper</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Character_Helper.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Character Helper</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Character" asp-action="Index">Characters</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Player" asp-action="Index">Players</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Character_Helper - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>